# Writes src/formats/esm/condition_functions.odin from xEdit's wbDefinitionsTES5.pas.
# Usage: ctda_table.py <wbDefinitionsTES5.pas>
import re, sys

FORM = {'ptActorBase', 'ptAssociationType', 'ptBaseObject', 'ptCell', 'ptClass', 'ptEffectItem',
        'ptEncounterZone', 'ptEquipType', 'ptEventData', 'ptFaction', 'ptFactionNull', 'ptFormList',
        'ptFurniture', 'ptGlobal', 'ptIdleForm', 'ptInventoryObject', 'ptKeyword', 'ptKnowable',
        'ptLocation', 'ptLocationRefType', 'ptMagicEffect', 'ptOwner', 'ptPerk', 'ptQuest', 'ptRace',
        'ptRegion', 'ptScene', 'ptShout', 'ptVoiceType', 'ptWeather', 'ptWorldSpace'}
REF = {'ptActor', 'ptReference', 'ptPackage'}
NUMBER = {'ptInteger', 'ptFloat', 'ptActorValue', 'ptAlignment', 'ptAxis', 'ptCastingSource',
          'ptCrimeType', 'ptCriticalStage', 'ptFormType', 'ptFurnitureAnim', 'ptFurnitureEntry',
          'ptMiscStat', 'ptPlayerAction', 'ptSex', 'ptVATSValueFunction', 'ptVATSValueParam',
          'ptWardState', 'ptAlias', 'ptPackdata', 'ptEvent', 'ptQuestStage'}

def kind(pt):
    if not pt: return '.None'
    if pt in FORM: return '.Form'
    if pt in REF: return '.Ref'
    if pt == 'ptString': return '.String'
    if pt in NUMBER: return '.Number'
    sys.exit(f'unknown parameter type {pt}')

src = open(sys.argv[1], encoding='latin1').read()
rows = re.findall(r"\(Index: *(\d+); Name: '([^']+)'(?:; ParamType1: (\w+))?(?:; ParamType2: (\w+))?", src)
top = max(int(i) for i, *_ in rows)
out = ['package esm', '',
       '// GENERATED by tools/ctda_table.py from xEdit (wbDefinitionsTES5.pas); do not edit.',
       '// Every condition function: its name and the kind of its two parameters.', '',
       f'CONDITION_FUNCTION_COUNT :: {top + 1}', '',
       '@(rodata)',
       'CONDITION_FUNCTIONS := [CONDITION_FUNCTION_COUNT]Condition_Function {']
for i, name, p1, p2 in rows:
    out.append(f'\t{i} = {{"{name}", {{{kind(p1)}, {kind(p2)}}}}},')
out.append('}')
open('src/formats/esm/condition_functions.odin', 'w').write('\n'.join(out) + '\n')
print(len(rows), 'functions')
